#pragma once

namespace TextureUniformConstants {
	const int LIGHT_SHADOW_TEXTURE_POSITION_START = 0;
	const int DIFFUSE_TEXTURE_POSTIION = 6;
	const int WATER_REFLECTION_TEXTURE_POSITION = DIFFUSE_TEXTURE_POSTIION;
	const int WATER_REFRACTION_TEXTURE_POSITION = DIFFUSE_TEXTURE_POSTIION + 1;
	const int SPECULAR_TEXTURE_POSTIION = 10;
	const int AMBIENT_TEXTURE_POSITION = 14;
	const int NORMAL_TEXTURE_POSITION = 18;
};
